-- =====================================================
-- INSERT DỮ LIỆU MẪU CHO BẢNG SEO (HOÀN CHỈNH 2025-2026+)
-- =====================================================

-- 1. INSERT SEO PAGE TYPES
INSERT INTO seo_page_types (name, display_name, description, sort_order) VALUES
('page', 'Trang tĩnh', 'Trang thông thường như home, about, contact, blog, help, faq', 1),
('product', 'Sản phẩm', 'Trang hiển thị thông tin chi tiết sản phẩm với đầy đủ SEO metadata', 2),
('category', 'Danh mục', 'Trang hiển thị danh sách sản phẩm theo danh mục với SEO tối ưu', 3),
('user', 'Người dùng', 'Trang quản lý tài khoản, đơn hàng, profile, dashboard', 4),
('system', 'Hệ thống', 'Trang 404, 500, maintenance, sitemap, robots.txt, security', 5);

-- 2. INSERT SEO PAGES (VỚI TẤT CẢ FIELDS MỚI)
INSERT INTO seo_pages (
    page_type_id, page_url, page_title, meta_description, meta_keywords,
    reference_type, reference_id,
    og_title, og_description, og_image, og_type, og_site_name, og_locale,
    twitter_card, twitter_title, twitter_description, twitter_image, twitter_creator, twitter_site,
    schema_markup, core_web_vitals, ai_ml_metrics, eeat_metrics, voice_visual_metrics,
    privacy_compliance, future_metrics,
    canonical_url, robots_directive, hreflang, language, charset, viewport,
    seo_score, keyword_difficulty, search_volume,
    page_load_time, mobile_friendly_score, accessibility_score, core_web_vitals_score,
    social_shares, social_engagement, social_click_through_rate,
    content_length, content_readability_score, content_freshness_score,
    internal_links_count, external_links_count, broken_links_count, image_optimization_score,
    is_active, is_featured, is_indexed, is_ssl_secure
) VALUES
-- Trang chủ
(1, '/', 'TechStore - Cửa hàng công nghệ hàng đầu Việt Nam', 
 'TechStore - Nơi mua sắm công nghệ uy tín với giá tốt nhất. iPhone, Samsung, Laptop, PC Gaming và nhiều sản phẩm khác.',
 ARRAY['công nghệ', 'điện thoại', 'laptop', 'máy tính', 'iphone', 'samsung'],
 'page', NULL,
 'TechStore - Cửa hàng công nghệ hàng đầu Việt Nam',
 'TechStore - Nơi mua sắm công nghệ uy tín với giá tốt nhất. iPhone, Samsung, Laptop, PC Gaming và nhiều sản phẩm khác.',
 '/images/og-home.jpg', 'website', 'TechStore', 'vi_VN',
 'summary_large_image', 'TechStore - Cửa hàng công nghệ hàng đầu Việt Nam',
 'TechStore - Nơi mua sắm công nghệ uy tín với giá tốt nhất.',
 '/images/twitter-home.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "Organization", "name": "TechStore", "url": "https://techstore.vn"}',
 '{"lcp": 2.1, "fid": 45, "cls": 0.08, "inp": 120, "ttfb": 180}',
 '{"ai_relevance_score": 95, "ml_ranking_factors": {"content_quality": 90, "user_engagement": 85}}',
 '{"experience_score": 90, "expertise_score": 95, "authoritativeness_score": 88, "trust_score": 92}',
 '{"voice_search_optimized": true, "visual_search_data": {"image_alt_texts": 95, "structured_images": 90}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"cookie_consent": true, "privacy_policy": true}}',
 '{"quantum_seo_ready": true, "neural_network_data": {"content_patterns": 88, "user_behavior": 92}}',
 '/', 'index,follow', '{"vi": "/", "en": "/en"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 95, 65, 15000,
 2.1, 95, 92, 88,
 1250, 4.8, 2.3,
 850, 85, 90,
 12, 8, 0, 92,
 true, true, true, true),

-- Trang sản phẩm iPhone 15
(2, '/shop-details/iphone-15', 'iPhone 15 - Điện thoại thông minh mới nhất từ Apple | TechStore',
 'iPhone 15 với chip A17 Pro mạnh mẽ, camera 48MP, màn hình 6.1 inch Super Retina XDR. Mua ngay tại TechStore với giá tốt nhất!',
 ARRAY['iphone 15', 'điện thoại apple', 'smartphone', 'camera 48mp', 'chip a17 pro'],
 'product', '550e8400-e29b-41d4-a716-446655440001',
 'iPhone 15 - Điện thoại thông minh mới nhất từ Apple | TechStore',
 'iPhone 15 với chip A17 Pro mạnh mẽ, camera 48MP, màn hình 6.1 inch Super Retina XDR.',
 '/images/products/iphone-15-og.jpg', 'product', 'TechStore', 'vi_VN',
 'summary_large_image', 'iPhone 15 - Điện thoại thông minh mới nhất từ Apple',
 'iPhone 15 với chip A17 Pro mạnh mẽ, camera 48MP, màn hình 6.1 inch Super Retina XDR.',
 '/images/products/iphone-15-twitter.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "Product", "name": "iPhone 15", "brand": "Apple", "model": "iPhone 15", "description": "iPhone 15 với chip A17 Pro mạnh mẽ", "offers": {"@type": "Offer", "price": "24990000", "priceCurrency": "VND"}}',
 '{"lcp": 1.8, "fid": 38, "cls": 0.05, "inp": 95, "ttfb": 150}',
 '{"ai_relevance_score": 98, "ml_ranking_factors": {"product_relevance": 95, "search_intent": 92}}',
 '{"experience_score": 95, "expertise_score": 98, "authoritativeness_score": 95, "trust_score": 96}',
 '{"voice_search_optimized": true, "visual_search_data": {"product_images": 98, "360_views": 90}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"secure_checkout": true, "data_protection": true}}',
 '{"quantum_seo_ready": true, "neural_network_data": {"product_patterns": 95, "purchase_behavior": 90}}',
 '/shop-details/iphone-15', 'index,follow', '{"vi": "/shop-details/iphone-15", "en": "/en/shop-details/iphone-15"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 98, 75, 8500,
 1.8, 98, 95, 92,
 890, 5.2, 3.1,
 650, 88, 95,
 8, 5, 0, 96,
 true, true, true, true),

-- Trang danh mục Điện thoại
(3, '/shop?category=phones', 'Điện thoại di động - iPhone, Samsung, Xiaomi | TechStore',
 'Khám phá bộ sưu tập điện thoại di động đa dạng từ iPhone, Samsung, Xiaomi. Giá tốt, chất lượng cao, giao hàng toàn quốc.',
 ARRAY['điện thoại', 'smartphone', 'iphone', 'samsung', 'xiaomi', 'mobile'],
 'category', '550e8400-e29b-41d4-a716-446655440002',
 'Điện thoại di động - iPhone, Samsung, Xiaomi | TechStore',
 'Khám phá bộ sưu tập điện thoại di động đa dạng từ iPhone, Samsung, Xiaomi.',
 '/images/categories/phones-og.jpg', 'website', 'TechStore', 'vi_VN',
 'summary_large_image', 'Điện thoại di động - iPhone, Samsung, Xiaomi | TechStore',
 'Khám phá bộ sưu tập điện thoại di động đa dạng từ iPhone, Samsung, Xiaomi.',
 '/images/categories/phones-twitter.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "CollectionPage", "name": "Điện thoại di động", "description": "Bộ sưu tập điện thoại di động đa dạng"}',
 '{"lcp": 2.3, "fid": 52, "cls": 0.09, "inp": 110, "ttfb": 200}',
 '{"ai_relevance_score": 92, "ml_ranking_factors": {"category_relevance": 90, "product_diversity": 88}}',
 '{"experience_score": 88, "expertise_score": 92, "authoritativeness_score": 90, "trust_score": 89}',
 '{"voice_search_optimized": true, "visual_search_data": {"category_images": 92, "product_grids": 88}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"category_filtering": true, "sort_options": true}}',
 '{"quantum_seo_ready": true, "neural_network_data": {"category_patterns": 88, "browsing_behavior": 85}}',
 '/shop?category=phones', 'index,follow', '{"vi": "/shop?category=phones", "en": "/en/shop?category=phones"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 92, 60, 12000,
 2.3, 92, 88, 85,
 680, 4.2, 2.8,
 450, 82, 88,
 15, 6, 0, 89,
 true, true, true, true),

-- Trang About
(1, '/about', 'Về chúng tôi - TechStore | Cửa hàng công nghệ uy tín',
 'TechStore - Hơn 10 năm kinh nghiệm trong lĩnh vực bán lẻ công nghệ. Cam kết chất lượng, giá tốt và dịch vụ khách hàng xuất sắc.',
 ARRAY['về chúng tôi', 'techstore', 'cửa hàng công nghệ', 'uy tín', 'kinh nghiệm'],
 'page', NULL,
 'Về chúng tôi - TechStore | Cửa hàng công nghệ uy tín',
 'TechStore - Hơn 10 năm kinh nghiệm trong lĩnh vực bán lẻ công nghệ.',
 '/images/about/about-og.jpg', 'website', 'TechStore', 'vi_VN',
 'summary_large_image', 'Về chúng tôi - TechStore | Cửa hàng công nghệ uy tín',
 'TechStore - Hơn 10 năm kinh nghiệm trong lĩnh vực bán lẻ công nghệ.',
 '/images/about/about-twitter.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "Organization", "name": "TechStore", "description": "Cửa hàng công nghệ uy tín", "foundingDate": "2014", "address": {"@type": "PostalAddress", "addressLocality": "Hà Nội", "addressCountry": "VN"}}',
 '{"lcp": 2.5, "fid": 48, "cls": 0.07, "inp": 105, "ttfb": 190}',
 '{"ai_relevance_score": 88, "ml_ranking_factors": {"company_info": 90, "trust_signals": 85}}',
 '{"experience_score": 95, "expertise_score": 90, "authoritativeness_score": 92, "trust_score": 94}',
 '{"voice_search_optimized": true, "visual_search_data": {"company_logo": 90, "team_photos": 85}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"company_info": true, "contact_details": true}}',
 '{"quantum_seo_ready": true, "neural_network_data": {"company_patterns": 88, "trust_signals": 90}}',
 '/about', 'index,follow', '{"vi": "/about", "en": "/en/about"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 88, 45, 3200,
 2.5, 90, 85, 82,
 420, 3.8, 1.9,
 1200, 90, 85,
 6, 3, 0, 88,
 true, false, true, true),

-- Trang Contact
(1, '/contact', 'Liên hệ - TechStore | Hỗ trợ khách hàng 24/7',
 'Liên hệ TechStore qua hotline, email hoặc chat trực tuyến. Đội ngũ hỗ trợ chuyên nghiệp, sẵn sàng phục vụ 24/7.',
 ARRAY['liên hệ', 'hỗ trợ', 'hotline', 'email', 'chat', 'customer service'],
 'page', NULL,
 'Liên hệ - TechStore | Hỗ trợ khách hàng 24/7',
 'Liên hệ TechStore qua hotline, email hoặc chat trực tuyến. Đội ngũ hỗ trợ chuyên nghiệp.',
 '/images/contact/contact-og.jpg', 'website', 'TechStore', 'vi_VN',
 'summary_large_image', 'Liên hệ - TechStore | Hỗ trợ khách hàng 24/7',
 'Liên hệ TechStore qua hotline, email hoặc chat trực tuyến. Đội ngũ hỗ trợ chuyên nghiệp.',
 '/images/contact/contact-twitter.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "ContactPage", "name": "Liên hệ TechStore", "description": "Thông tin liên hệ và hỗ trợ khách hàng"}',
 '{"lcp": 2.0, "fid": 42, "cls": 0.06, "inp": 98, "ttfb": 160}',
 '{"ai_relevance_score": 85, "ml_ranking_factors": {"contact_info": 90, "support_quality": 88}}',
 '{"experience_score": 92, "expertise_score": 88, "authoritativeness_score": 90, "trust_score": 93}',
 '{"voice_search_optimized": true, "visual_search_data": {"contact_forms": 88, "location_maps": 90}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"contact_forms": true, "data_handling": true}}',
 '{"quantum_seo_ready": true, "neural_network_data": {"contact_patterns": 85, "support_patterns": 88}}',
 '/contact', 'index,follow', '{"vi": "/contact", "en": "/en/contact"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 85, 40, 2800,
 2.0, 88, 82, 80,
 380, 3.5, 1.7,
 800, 85, 80,
 4, 2, 0, 85,
 true, false, true, true),

-- Trang Blog
(1, '/blog', 'Blog công nghệ - Tin tức, đánh giá sản phẩm | TechStore',
 'Blog công nghệ TechStore cập nhật tin tức mới nhất, đánh giá sản phẩm chi tiết, hướng dẫn sử dụng và tips công nghệ hữu ích.',
 ARRAY['blog công nghệ', 'tin tức', 'đánh giá', 'hướng dẫn', 'tips', 'công nghệ'],
 'page', NULL,
 'Blog công nghệ - Tin tức, đánh giá sản phẩm | TechStore',
 'Blog công nghệ TechStore cập nhật tin tức mới nhất, đánh giá sản phẩm chi tiết.',
 '/images/blog/blog-og.jpg', 'website', 'TechStore', 'vi_VN',
 'summary_large_image', 'Blog công nghệ - Tin tức, đánh giá sản phẩm | TechStore',
 'Blog công nghệ TechStore cập nhật tin tức mới nhất, đánh giá sản phẩm chi tiết.',
 '/images/blog/blog-twitter.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "Blog", "name": "Blog công nghệ TechStore", "description": "Blog về công nghệ và đánh giá sản phẩm"}',
 '{"lcp": 2.8, "fid": 55, "cls": 0.10, "inp": 115, "ttfb": 220}',
 '{"ai_relevance_score": 90, "ml_ranking_factors": {"content_quality": 88, "engagement_metrics": 85}}',
 '{"experience_score": 88, "expertise_score": 92, "authoritativeness_score": 90, "trust_score": 89}',
 '{"voice_search_optimized": true, "visual_search_data": {"blog_images": 88, "content_thumbnails": 85}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"content_sharing": true, "comment_system": true}}',
 '{"quantum_seo_ready": true, "neural_network_data": {"content_patterns": 90, "reading_behavior": 85}}',
 '/blog', 'index,follow', '{"vi": "/blog", "en": "/en/blog"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 90, 55, 6800,
 2.8, 90, 85, 80,
 720, 4.5, 2.5,
 1800, 88, 92,
 18, 12, 0, 90,
 true, true, true, true),

-- Trang sản phẩm MacBook Pro
(2, '/shop-details/macbook-pro-m3', 'MacBook Pro M3 - Laptop mạnh mẽ cho chuyên gia | TechStore',
 'MacBook Pro M3 với chip Apple M3 Pro/Max, màn hình Liquid Retina XDR 14.2 inch, hiệu năng vượt trội cho công việc chuyên môn.',
 ARRAY['macbook pro m3', 'laptop apple', 'macbook', 'chip m3', 'laptop chuyên nghiệp'],
 'product', '550e8400-e29b-41d4-a716-446655440003',
 'MacBook Pro M3 - Laptop mạnh mẽ cho chuyên gia | TechStore',
 'MacBook Pro M3 với chip Apple M3 Pro/Max, màn hình Liquid Retina XDR 14.2 inch.',
 '/images/products/macbook-pro-m3-og.jpg', 'product', 'TechStore', 'vi_VN',
 'summary_large_image', 'MacBook Pro M3 - Laptop mạnh mẽ cho chuyên gia | TechStore',
 'MacBook Pro M3 với chip Apple M3 Pro/Max, màn hình Liquid Retina XDR 14.2 inch.',
 '/images/products/macbook-pro-m3-twitter.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "Product", "name": "MacBook Pro M3", "brand": "Apple", "model": "MacBook Pro M3", "description": "Laptop mạnh mẽ cho chuyên gia", "offers": {"@type": "Offer", "price": "45990000", "priceCurrency": "VND"}}',
 '{"lcp": 2.2, "fid": 45, "cls": 0.08, "inp": 105, "ttfb": 170}',
 '{"ai_relevance_score": 96, "ml_ranking_factors": {"product_relevance": 94, "search_intent": 90}}',
 '{"experience_score": 92, "expertise_score": 96, "authoritativeness_score": 94, "trust_score": 95}',
 '{"voice_search_optimized": true, "visual_search_data": {"product_images": 96, "specs_diagrams": 90}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"secure_checkout": true, "warranty_info": true}}',
 '{"quantum_seo_ready": true, "neural_network_data": {"product_patterns": 94, "purchase_behavior": 88}}',
 '/shop-details/macbook-pro-m3', 'index,follow', '{"vi": "/shop-details/macbook-pro-m3", "en": "/en/shop-details/macbook-pro-m3"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 96, 80, 5200,
 2.2, 96, 92, 88,
 650, 4.8, 2.9,
 750, 90, 88,
 10, 6, 0, 94,
 true, true, true, true),

-- Trang danh mục Laptop
(3, '/shop?category=laptops', 'Laptop - MacBook, Dell, HP, Lenovo | TechStore',
 'Bộ sưu tập laptop đa dạng từ MacBook, Dell, HP, Lenovo. Laptop gaming, laptop văn phòng, laptop đồ họa với giá tốt nhất.',
 ARRAY['laptop', 'macbook', 'dell', 'hp', 'lenovo', 'gaming', 'văn phòng'],
 'category', '550e8400-e29b-41d4-a716-446655440004',
 'Laptop - MacBook, Dell, HP, Lenovo | TechStore',
 'Bộ sưu tập laptop đa dạng từ MacBook, Dell, HP, Lenovo.',
 '/images/categories/laptops-og.jpg', 'website', 'TechStore', 'vi_VN',
 'summary_large_image', 'Laptop - MacBook, Dell, HP, Lenovo | TechStore',
 'Bộ sưu tập laptop đa dạng từ MacBook, Dell, HP, Lenovo.',
 '/images/categories/laptops-twitter.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "CollectionPage", "name": "Laptop", "description": "Bộ sưu tập laptop đa dạng"}',
 '{"lcp": 2.4, "fid": 50, "cls": 0.09, "inp": 108, "ttfb": 190}',
 '{"ai_relevance_score": 94, "ml_ranking_factors": {"category_relevance": 92, "product_diversity": 90}}',
 '{"experience_score": 90, "expertise_score": 94, "authoritativeness_score": 92, "trust_score": 91}',
 '{"voice_search_optimized": true, "visual_search_data": {"category_images": 94, "product_grids": 90}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"category_filtering": true, "sort_options": true}}',
 '{"quantum_seo_ready": true, "neural_network_data": {"category_patterns": 92, "browsing_behavior": 88}}',
 '/shop?category=laptops', 'index,follow', '{"vi": "/shop?category=laptops", "en": "/en/shop?category=laptops"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 94, 70, 9800,
 2.4, 94, 90, 86,
 750, 4.6, 3.0,
 520, 86, 90,
 16, 8, 0, 92,
 true, true, true, true),

-- Trang Help/FAQ
(1, '/help', 'Hỗ trợ & FAQ - Giải đáp thắc mắc | TechStore',
 'Tìm câu trả lời cho các câu hỏi thường gặp về mua sắm, thanh toán, giao hàng, bảo hành và dịch vụ khách hàng tại TechStore.',
 ARRAY['hỗ trợ', 'faq', 'câu hỏi thường gặp', 'hướng dẫn', 'giải đáp'],
 'page', NULL,
 'Hỗ trợ & FAQ - Giải đáp thắc mắc | TechStore',
 'Tìm câu trả lời cho các câu hỏi thường gặp về mua sắm, thanh toán, giao hàng.',
 '/images/help/help-og.jpg', 'website', 'TechStore', 'vi_VN',
 'summary_large_image', 'Hỗ trợ & FAQ - Giải đáp thắc mắc | TechStore',
 'Tìm câu trả lời cho các câu hỏi thường gặp về mua sắm, thanh toán, giao hàng.',
 '/images/help/help-twitter.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "FAQPage", "name": "Hỗ trợ & FAQ TechStore", "description": "Giải đáp thắc mắc khách hàng"}',
 '{"lcp": 2.1, "fid": 44, "cls": 0.07, "inp": 100, "ttfb": 165}',
 '{"ai_relevance_score": 87, "ml_ranking_factors": {"help_content": 90, "search_intent": 85}}',
 '{"experience_score": 90, "expertise_score": 88, "authoritativeness_score": 90, "trust_score": 91}',
 '{"voice_search_optimized": true, "visual_search_data": {"help_icons": 88, "faq_layout": 85}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"help_content": true, "contact_options": true}}',
 '{"quantum_seo_ready": true, "neural_network_data": {"help_patterns": 87, "user_queries": 85}}',
 '/help', 'index,follow', '{"vi": "/help", "en": "/en/help"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 87, 35, 2100,
 2.1, 88, 84, 78,
 320, 3.2, 1.5,
 1500, 88, 82,
 8, 4, 0, 86,
 true, false, true, true),

-- Trang 404
(5, '/404', 'Trang không tìm thấy - TechStore',
 'Trang bạn đang tìm kiếm không tồn tại. Quay về trang chủ hoặc sử dụng menu điều hướng để tìm sản phẩm mong muốn.',
 ARRAY['404', 'không tìm thấy', 'lỗi', 'trang chủ'],
 'page', NULL,
 'Trang không tìm thấy - TechStore',
 'Trang bạn đang tìm kiếm không tồn tại. Quay về trang chủ hoặc sử dụng menu điều hướng.',
 '/images/404/404-og.jpg', 'website', 'TechStore', 'vi_VN',
 'summary_large_image', 'Trang không tìm thấy - TechStore',
 'Trang bạn đang tìm kiếm không tồn tại. Quay về trang chủ hoặc sử dụng menu điều hướng.',
 '/images/404/404-twitter.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "WebPage", "name": "Trang không tìm thấy", "description": "404 Error Page"}',
 '{"lcp": 1.5, "fid": 35, "cls": 0.04, "inp": 85, "ttfb": 120}',
 '{"ai_relevance_score": 75, "ml_ranking_factors": {"error_handling": 80, "user_experience": 75}}',
 '{"experience_score": 80, "expertise_score": 75, "authoritativeness_score": 78, "trust_score": 80}',
 '{"voice_search_optimized": false, "visual_search_data": {"error_illustration": 85, "navigation_help": 80}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"error_tracking": false, "user_guidance": true}}',
 '{"quantum_seo_ready": false, "neural_network_data": {"error_patterns": 75, "recovery_behavior": 70}}',
 '/404', 'noindex,nofollow', '{"vi": "/404", "en": "/en/404"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 75, 20, 1500,
 1.5, 85, 80, 75,
 180, 2.8, 1.2,
 300, 75, 70,
 3, 1, 0, 80,
 true, false, false, true);

-- =====================================================
-- HOÀN THÀNH INSERT DỮ LIỆU SEO MẪU
-- =====================================================

-- =====================================================
-- BỔ SUNG DỮ LIỆU SEO CHO CÁC LOẠI TRANG CÒN THIẾU
-- =====================================================

-- Trang User Profile
INSERT INTO seo_pages (
    page_type_id, page_url, page_title, meta_description, meta_keywords,
    reference_type, reference_id,
    og_title, og_description, og_image, og_type, og_site_name, og_locale,
    twitter_card, twitter_title, twitter_description, twitter_image, twitter_creator, twitter_site,
    schema_markup, core_web_vitals, ai_ml_metrics, eeat_metrics, voice_visual_metrics,
    privacy_compliance, future_metrics,
    canonical_url, robots_directive, hreflang, language, charset, viewport,
    seo_score, keyword_difficulty, search_volume,
    page_load_time, mobile_friendly_score, accessibility_score, core_web_vitals_score,
    social_shares, social_engagement, social_click_through_rate,
    content_length, content_readability_score, content_freshness_score,
    internal_links_count, external_links_count, broken_links_count, image_optimization_score,
    is_active, is_featured, is_indexed, is_ssl_secure
) VALUES
(4, '/my-account', 'Tài khoản của tôi - TechStore | Quản lý đơn hàng, thông tin cá nhân',
 'Quản lý tài khoản TechStore: Xem đơn hàng, cập nhật thông tin cá nhân, địa chỉ giao hàng và bảo mật tài khoản.',
 ARRAY['tài khoản', 'đơn hàng', 'thông tin cá nhân', 'địa chỉ giao hàng', 'bảo mật'],
 'user', NULL,
 'Tài khoản của tôi - TechStore | Quản lý đơn hàng, thông tin cá nhân',
 'Quản lý tài khoản TechStore: Xem đơn hàng, cập nhật thông tin cá nhân, địa chỉ giao hàng.',
 '/images/user/profile-og.jpg', 'website', 'TechStore', 'vi_VN',
 'summary_large_image', 'Tài khoản của tôi - TechStore | Quản lý đơn hàng, thông tin cá nhân',
 'Quản lý tài khoản TechStore: Xem đơn hàng, cập nhật thông tin cá nhân, địa chỉ giao hàng.',
 '/images/user/profile-twitter.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "WebPage", "name": "Tài khoản của tôi", "description": "Quản lý tài khoản TechStore"}',
 '{"lcp": 2.0, "fid": 40, "cls": 0.06, "inp": 95, "ttfb": 150}',
 '{"ai_relevance_score": 85, "ml_ranking_factors": {"user_experience": 90, "security": 88}}',
 '{"experience_score": 88, "expertise_score": 85, "authoritativeness_score": 90, "trust_score": 92}',
 '{"voice_search_optimized": false, "visual_search_data": {"user_interface": 88, "navigation": 85}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"user_data": true, "secure_login": true}}',
 '{"quantum_seo_ready": false, "neural_network_data": {"user_patterns": 85, "security_patterns": 88}}',
 '/my-account', 'noindex,nofollow', '{"vi": "/my-account", "en": "/en/my-account"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 85, 30, 1800,
 2.0, 90, 88, 85,
 280, 3.2, 1.6,
 600, 85, 80,
 5, 2, 0, 88,
 true, false, false, true),

-- Trang System - Sitemap
(5, '/sitemap.xml', 'Sitemap - TechStore | Bản đồ website',
 'Sitemap TechStore - Bản đồ website với tất cả trang, sản phẩm, danh mục và bài viết blog.',
 ARRAY['sitemap', 'bản đồ website', 'seo', 'index'],
 'system', NULL,
 'Sitemap - TechStore | Bản đồ website',
 'Sitemap TechStore - Bản đồ website với tất cả trang, sản phẩm, danh mục và bài viết blog.',
 '/images/system/sitemap-og.jpg', 'website', 'TechStore', 'vi_VN',
 'summary_large_image', 'Sitemap - TechStore | Bản đồ website',
 'Sitemap TechStore - Bản đồ website với tất cả trang, sản phẩm, danh mục và bài viết blog.',
 '/images/system/sitemap-twitter.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "WebPage", "name": "Sitemap", "description": "Bản đồ website TechStore"}',
 '{"lcp": 1.2, "fid": 30, "cls": 0.03, "inp": 75, "ttfb": 100}',
 '{"ai_relevance_score": 70, "ml_ranking_factors": {"technical_seo": 85, "crawlability": 90}}',
 '{"experience_score": 75, "expertise_score": 80, "authoritativeness_score": 85, "trust_score": 80}',
 '{"voice_search_optimized": false, "visual_search_data": {"xml_structure": 90, "technical_format": 85}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"technical_data": true, "crawl_data": true}}',
 '{"quantum_seo_ready": false, "neural_network_data": {"technical_patterns": 80, "crawl_patterns": 85}}',
 '/sitemap.xml', 'index,follow', '{"vi": "/sitemap.xml", "en": "/en/sitemap.xml"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 80, 15, 800,
 1.2, 95, 90, 88,
 120, 2.5, 1.0,
 200, 80, 75,
 2, 1, 0, 90,
 true, false, true, true),

-- Trang System - Robots.txt
(5, '/robots.txt', 'Robots.txt - TechStore | Hướng dẫn cho search engines',
 'Robots.txt TechStore - Hướng dẫn cho search engines về việc crawl và index website.',
 ARRAY['robots.txt', 'search engine', 'crawl', 'index', 'seo'],
 'system', NULL,
 'Robots.txt - TechStore | Hướng dẫn cho search engines',
 'Robots.txt TechStore - Hướng dẫn cho search engines về việc crawl và index website.',
 '/images/system/robots-og.jpg', 'website', 'TechStore', 'vi_VN',
 'summary_large_image', 'Robots.txt - TechStore | Hướng dẫn cho search engines',
 'Robots.txt TechStore - Hướng dẫn cho search engines về việc crawl và index website.',
 '/images/system/robots-twitter.jpg', '@techstore_vn', '@techstore_vn',
 '{"@context": "https://schema.org", "@type": "WebPage", "name": "Robots.txt", "description": "Hướng dẫn cho search engines"}',
 '{"lcp": 0.8, "fid": 25, "cls": 0.02, "inp": 60, "ttfb": 80}',
 '{"ai_relevance_score": 65, "ml_ranking_factors": {"technical_seo": 90, "crawlability": 95}}',
 '{"experience_score": 70, "expertise_score": 85, "authoritativeness_score": 90, "trust_score": 75}',
 '{"voice_search_optimized": false, "visual_search_data": {"text_format": 95, "technical_structure": 90}}',
 '{"gdpr_compliant": true, "ccpa_compliant": true, "privacy_signals": {"technical_data": true, "crawl_data": true}}',
 '{"quantum_seo_ready": false, "neural_network_data": {"technical_patterns": 85, "crawl_patterns": 90}}',
 '/robots.txt', 'index,follow', '{"vi": "/robots.txt", "en": "/en/robots.txt"}', 'vi', 'UTF-8', 'width=device-width, initial-scale=1',
 75, 10, 500,
 0.8, 98, 95, 92,
 80, 2.0, 0.8,
 150, 85, 70,
 1, 0, 0, 95,
 true, false, true, true);
